[package]
name = "alaric-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "net", "time", "io-util", "signal"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
lib = { path = "../lib" }
